"""Public surface for the OpenAgentBench agent-data module."""

from .compiler import ContextCompiler, allocate_budget, classify_task_type, format_memory_block
from .enums import (
    FinishReason,
    MemoryScope,
    MemoryTier,
    MessageRole,
    ProvenanceType,
    SessionStatus,
    TaskType,
)
from .json_codec import canonical_json_bytes, dumps, hash_normalized_text, loads, normalize_text
from .models import (
    APIInvocationRecord,
    APIStreamEventRecord,
    ChatMessage,
    CompileRequest,
    CompiledContext,
    ContextBudget,
    HistoryRecord,
    MemoryRecord,
    ProtocolEventRecord,
    QueryTemplate,
    ScoredMemory,
    SessionRecord,
)
from .openai_catalog import OPENAI_ENDPOINTS, OpenAIEndpointSpec, endpoints_for_modality
from .vllm_catalog import VLLM_ENDPOINTS, VLLMEndpointSpec, vllm_endpoints_for_modality
from .packing import pack_memories, select_contiguous_history_suffix
from .queries import (
    build_fetch_active_history,
    build_fetch_keyword_memories,
    build_fetch_semantic_memories,
    build_insert_api_invocation,
    build_insert_history,
    build_insert_protocol_event,
    build_insert_session,
    build_insert_stream_event,
    build_upsert_memory,
)
from .scoring import PROMOTION_RULES, RetrievalWeights, compute_memory_score, promotion_utility, score_memories

__all__ = [
    "ChatMessage",
    "CompileRequest",
    "CompiledContext",
    "ContextBudget",
    "ContextCompiler",
    "APIInvocationRecord",
    "APIStreamEventRecord",
    "FinishReason",
    "HistoryRecord",
    "MemoryRecord",
    "MemoryScope",
    "MemoryTier",
    "MessageRole",
    "OPENAI_ENDPOINTS",
    "OpenAIEndpointSpec",
    "VLLM_ENDPOINTS",
    "VLLMEndpointSpec",
    "PROMOTION_RULES",
    "ProtocolEventRecord",
    "ProvenanceType",
    "QueryTemplate",
    "RetrievalWeights",
    "ScoredMemory",
    "SessionRecord",
    "SessionStatus",
    "TaskType",
    "allocate_budget",
    "build_fetch_active_history",
    "build_fetch_keyword_memories",
    "build_fetch_semantic_memories",
    "build_insert_api_invocation",
    "build_insert_history",
    "build_insert_protocol_event",
    "build_insert_session",
    "build_insert_stream_event",
    "build_upsert_memory",
    "canonical_json_bytes",
    "classify_task_type",
    "compute_memory_score",
    "dumps",
    "endpoints_for_modality",
    "format_memory_block",
    "hash_normalized_text",
    "loads",
    "normalize_text",
    "pack_memories",
    "promotion_utility",
    "score_memories",
    "select_contiguous_history_suffix",
    "vllm_endpoints_for_modality",
]
