"""OpenAI endpoint catalog for multimodal compatibility, routing, and docs coverage."""

from __future__ import annotations

from dataclasses import dataclass

_API_OVERVIEW_URL = "https://developers.openai.com/api/reference/overview"


@dataclass(slots=True, frozen=True)
class OpenAIEndpointSpec:
    name: str
    path: str
    python_sdk_call: str
    input_modalities: tuple[str, ...]
    output_modalities: tuple[str, ...]
    supports_mixed_content: bool
    notes: str
    source_url: str
    category: str = "platform"
    lifecycle: str = "stable"
    documented_operations: tuple[str, ...] = ()
    documented_subresources: tuple[str, ...] = ()


def _endpoint(
    *,
    name: str,
    path: str,
    python_sdk_call: str,
    input_modalities: tuple[str, ...],
    output_modalities: tuple[str, ...],
    supports_mixed_content: bool,
    notes: str,
    source_url: str = _API_OVERVIEW_URL,
    category: str = "platform",
    lifecycle: str = "stable",
    documented_operations: tuple[str, ...] = (),
    documented_subresources: tuple[str, ...] = (),
) -> OpenAIEndpointSpec:
    return OpenAIEndpointSpec(
        name=name,
        path=path,
        python_sdk_call=python_sdk_call,
        input_modalities=input_modalities,
        output_modalities=output_modalities,
        supports_mixed_content=supports_mixed_content,
        notes=notes,
        source_url=source_url,
        category=category,
        lifecycle=lifecycle,
        documented_operations=documented_operations,
        documented_subresources=documented_subresources,
    )


OPENAI_ENDPOINTS: tuple[OpenAIEndpointSpec, ...] = (
    _endpoint(
        name="responses",
        path="/v1/responses",
        python_sdk_call="client.responses.create(...)",
        input_modalities=("text", "image", "audio", "file", "mixed"),
        output_modalities=("text", "audio", "tool_calls", "structured_data"),
        supports_mixed_content=True,
        notes="Primary unified OpenAI endpoint with stateful multimodal and tool-using support.",
        category="responses_api",
        documented_operations=("create", "retrieve", "delete", "list_input_items", "count_input_tokens", "cancel", "compact"),
        documented_subresources=(
            "/v1/responses/{response_id}",
            "/v1/responses/{response_id}/input_items",
            "/v1/responses/{response_id}/cancel",
            "/v1/responses/{response_id}/compact",
        ),
    ),
    _endpoint(
        name="conversations",
        path="/v1/conversations",
        python_sdk_call="client.conversations.create(...)",
        input_modalities=("text", "image", "audio", "mixed"),
        output_modalities=("structured_data",),
        supports_mixed_content=True,
        notes="Conversation state surface paired with the Responses API item graph.",
        category="responses_api",
        documented_operations=("create", "retrieve", "update", "delete", "create_item", "retrieve_item", "delete_item", "list_items"),
        documented_subresources=(
            "/v1/conversations/{conversation_id}",
            "/v1/conversations/{conversation_id}/items",
            "/v1/conversations/{conversation_id}/items/{item_id}",
        ),
    ),
    _endpoint(
        name="chat_completions",
        path="/v1/chat/completions",
        python_sdk_call="client.chat.completions.create(...)",
        input_modalities=("text", "image", "audio", "mixed"),
        output_modalities=("text", "audio", "tool_calls", "structured_data"),
        supports_mixed_content=True,
        notes="Chat Completions remains available for message-list based applications and migrations.",
        category="platform",
        documented_operations=("create", "list", "stream_events"),
    ),
    _endpoint(
        name="audio_speech",
        path="/v1/audio/speech",
        python_sdk_call="client.audio.speech.create(...)",
        input_modalities=("text",),
        output_modalities=("audio",),
        supports_mixed_content=False,
        notes="Text-to-speech generation surface.",
        category="audio",
        documented_operations=("create",),
    ),
    _endpoint(
        name="audio_transcriptions",
        path="/v1/audio/transcriptions",
        python_sdk_call="client.audio.transcriptions.create(...)",
        input_modalities=("audio",),
        output_modalities=("text", "structured_data"),
        supports_mixed_content=False,
        notes="Speech-to-text transcription surface.",
        category="audio",
        documented_operations=("create",),
    ),
    _endpoint(
        name="audio_translations",
        path="/v1/audio/translations",
        python_sdk_call="client.audio.translations.create(...)",
        input_modalities=("audio",),
        output_modalities=("text", "structured_data"),
        supports_mixed_content=False,
        notes="Audio translation surface for speech-to-English workflows.",
        category="audio",
        documented_operations=("create",),
    ),
    _endpoint(
        name="audio_voices",
        path="/v1/audio/voices",
        python_sdk_call="client.audio.voices.create(...)",
        input_modalities=("audio", "text", "mixed"),
        output_modalities=("structured_data",),
        supports_mixed_content=True,
        notes="Voice creation surface for reusable voice identities.",
        category="audio",
        documented_operations=("create",),
    ),
    _endpoint(
        name="audio_voice_consents",
        path="/v1/audio/voice_consents",
        python_sdk_call="client.audio.voice_consents.create(...)",
        input_modalities=("audio", "text", "mixed"),
        output_modalities=("structured_data",),
        supports_mixed_content=True,
        notes="Voice consent lifecycle for voice-cloning safety requirements.",
        source_url="https://developers.openai.com/api/reference/resources/audio/subresources/voice_consents/methods/create",
        category="audio",
        documented_operations=("create", "retrieve", "update", "delete", "list"),
        documented_subresources=("/v1/audio/voice_consents/{consent_id}",),
    ),
    _endpoint(
        name="videos",
        path="/v1/videos",
        python_sdk_call="client.videos.generate(...)",
        input_modalities=("text", "image", "video", "mixed"),
        output_modalities=("video", "audio", "structured_data"),
        supports_mixed_content=True,
        notes="Video generation surface including create, retrieve, download, edit, extend, and remix flows.",
        category="video",
        documented_operations=("create", "retrieve", "delete", "list", "download_content", "edit", "extend", "remix"),
        documented_subresources=(
            "/v1/videos/characters",
            "/v1/videos/characters/{character_id}",
            "/v1/videos/{video_id}",
            "/v1/videos/{video_id}/content",
            "/v1/videos/{video_id}/edit",
            "/v1/videos/{video_id}/extend",
            "/v1/videos/{video_id}/remix",
        ),
    ),
    _endpoint(
        name="images_generations",
        path="/v1/images/generations",
        python_sdk_call="client.images.generate(...)",
        input_modalities=("text", "image", "mixed"),
        output_modalities=("image", "structured_data"),
        supports_mixed_content=True,
        notes="Image generation surface with streaming event documentation.",
        category="images",
        documented_operations=("create", "stream_events"),
    ),
    _endpoint(
        name="images_edits",
        path="/v1/images/edits",
        python_sdk_call="client.images.edit(...)",
        input_modalities=("text", "image", "mask", "mixed"),
        output_modalities=("image", "structured_data"),
        supports_mixed_content=True,
        notes="Image editing surface with optional mask and streaming events.",
        category="images",
        documented_operations=("create", "stream_events"),
    ),
    _endpoint(
        name="images_variations",
        path="/v1/images/variations",
        python_sdk_call="client.images.create_variation(...)",
        input_modalities=("image",),
        output_modalities=("image", "structured_data"),
        supports_mixed_content=False,
        notes="Image variation surface for generating alternatives from an input image.",
        category="images",
        documented_operations=("create",),
    ),
    _endpoint(
        name="embeddings",
        path="/v1/embeddings",
        python_sdk_call="client.embeddings.create(...)",
        input_modalities=("text",),
        output_modalities=("embedding",),
        supports_mixed_content=False,
        notes="Embedding generation surface for retrieval and ranking.",
        category="embeddings",
        documented_operations=("create",),
    ),
    _endpoint(
        name="evals",
        path="/v1/evals",
        python_sdk_call="client.evals.create(...)",
        input_modalities=("text", "file", "mixed"),
        output_modalities=("structured_data",),
        supports_mixed_content=True,
        notes="Evaluation management surface with run orchestration and output item inspection.",
        category="evals",
        documented_operations=("create", "retrieve", "update", "delete", "list", "create_run", "retrieve_run", "delete_run", "list_runs", "cancel_run", "retrieve_output_item", "list_output_items"),
        documented_subresources=(
            "/v1/evals/{eval_id}",
            "/v1/evals/{eval_id}/runs",
            "/v1/evals/{eval_id}/runs/{run_id}",
            "/v1/evals/{eval_id}/runs/{run_id}/cancel",
            "/v1/evals/{eval_id}/runs/{run_id}/output_items",
            "/v1/evals/{eval_id}/runs/{run_id}/output_items/{item_id}",
        ),
    ),
    _endpoint(
        name="fine_tuning_jobs",
        path="/v1/fine_tuning/jobs",
        python_sdk_call="client.fine_tuning.jobs.create(...)",
        input_modalities=("file", "text"),
        output_modalities=("structured_data",),
        supports_mixed_content=False,
        notes="Fine-tuning job lifecycle including events, pause/resume, checkpoints, and checkpoint permissions.",
        category="fine_tuning",
        documented_operations=("create", "retrieve", "list", "list_events", "cancel", "pause", "resume", "list_checkpoints", "create_checkpoint_permission", "retrieve_checkpoint_permission", "delete_checkpoint_permission", "list_checkpoint_permissions", "alpha_run_grader", "alpha_validate_grader"),
        documented_subresources=(
            "/v1/fine_tuning/jobs/{job_id}",
            "/v1/fine_tuning/jobs/{job_id}/events",
            "/v1/fine_tuning/jobs/{job_id}/cancel",
            "/v1/fine_tuning/jobs/{job_id}/pause",
            "/v1/fine_tuning/jobs/{job_id}/resume",
            "/v1/fine_tuning/jobs/{job_id}/checkpoints",
            "/v1/fine_tuning/checkpoints/{checkpoint_id}/permissions",
        ),
    ),
    _endpoint(
        name="batches",
        path="/v1/batches",
        python_sdk_call="client.batches.create(...)",
        input_modalities=("file",),
        output_modalities=("structured_data",),
        supports_mixed_content=False,
        notes="Batch execution surface for asynchronous large-scale processing.",
        category="batch",
        documented_operations=("create", "retrieve", "list", "cancel"),
        documented_subresources=(
            "/v1/batches/{batch_id}",
            "/v1/batches/{batch_id}/cancel",
        ),
    ),
    _endpoint(
        name="files",
        path="/v1/files",
        python_sdk_call="client.files.create(...)",
        input_modalities=("file", "text"),
        output_modalities=("structured_data", "file"),
        supports_mixed_content=False,
        notes="General file storage surface used across fine-tuning, batches, retrieval, and tool workflows.",
        category="files",
        documented_operations=("list", "create", "retrieve", "delete", "retrieve_content"),
        documented_subresources=(
            "/v1/files/{file_id}",
            "/v1/files/{file_id}/content",
        ),
    ),
    _endpoint(
        name="uploads",
        path="/v1/uploads",
        python_sdk_call="client.uploads.create(...)",
        input_modalities=("file",),
        output_modalities=("structured_data",),
        supports_mixed_content=False,
        notes="Multipart upload session surface used for larger file ingestion.",
        category="files",
        documented_operations=("create", "cancel", "complete", "create_part"),
        documented_subresources=(
            "/v1/uploads/{upload_id}",
            "/v1/uploads/{upload_id}/cancel",
            "/v1/uploads/{upload_id}/complete",
            "/v1/uploads/{upload_id}/parts",
        ),
    ),
    _endpoint(
        name="models",
        path="/v1/models",
        python_sdk_call="client.models.list()",
        input_modalities=(),
        output_modalities=("structured_data",),
        supports_mixed_content=False,
        notes="Model registry surface for listing, retrieving, and deleting model objects.",
        category="models",
        documented_operations=("retrieve", "delete", "list"),
        documented_subresources=("/v1/models/{model_id}",),
    ),
    _endpoint(
        name="moderations",
        path="/v1/moderations",
        python_sdk_call="client.moderations.create(...)",
        input_modalities=("text", "image", "mixed"),
        output_modalities=("structured_data", "safety_labels"),
        supports_mixed_content=True,
        notes="Safety classification surface for text and image policy checks.",
        category="safety",
        documented_operations=("create",),
    ),
    _endpoint(
        name="vector_stores",
        path="/v1/vector_stores",
        python_sdk_call="client.vector_stores.create(...)",
        input_modalities=("file", "text"),
        output_modalities=("structured_data",),
        supports_mixed_content=False,
        notes="Retrieval storage surface with file and file-batch management plus search.",
        category="retrieval",
        documented_operations=("create", "retrieve", "update", "delete", "list", "search", "list_files", "create_file", "retrieve_file", "update_file", "delete_file", "retrieve_file_content", "create_file_batch", "retrieve_file_batch", "list_file_batch_files", "cancel_file_batch"),
        documented_subresources=(
            "/v1/vector_stores/{vector_store_id}",
            "/v1/vector_stores/{vector_store_id}/search",
            "/v1/vector_stores/{vector_store_id}/files",
            "/v1/vector_stores/{vector_store_id}/files/{file_id}",
            "/v1/vector_stores/{vector_store_id}/files/{file_id}/content",
            "/v1/vector_stores/{vector_store_id}/file_batches",
            "/v1/vector_stores/{vector_store_id}/file_batches/{batch_id}",
            "/v1/vector_stores/{vector_store_id}/file_batches/{batch_id}/files",
        ),
    ),
    _endpoint(
        name="chatkit_sessions",
        path="/v1/chatkit/sessions",
        python_sdk_call="client.beta.chatkit.sessions.create(...)",
        input_modalities=("text", "image", "audio", "mixed"),
        output_modalities=("structured_data",),
        supports_mixed_content=True,
        notes="ChatKit beta session orchestration surface.",
        category="chatkit",
        lifecycle="beta",
        documented_operations=("create", "cancel"),
        documented_subresources=("/v1/chatkit/sessions/{session_id}/cancel",),
    ),
    _endpoint(
        name="chatkit_threads",
        path="/v1/chatkit/threads",
        python_sdk_call="client.beta.chatkit.threads.list(...)",
        input_modalities=("text", "image", "audio", "mixed"),
        output_modalities=("structured_data",),
        supports_mixed_content=True,
        notes="ChatKit beta thread inspection surface.",
        source_url="https://developers.openai.com/api/reference/resources/beta/subresources/chatkit/subresources/threads/methods/retrieve",
        category="chatkit",
        lifecycle="beta",
        documented_operations=("retrieve", "delete", "list_items", "list"),
        documented_subresources=(
            "/v1/chatkit/threads/{thread_id}",
            "/v1/chatkit/threads/{thread_id}/items",
        ),
    ),
    _endpoint(
        name="containers",
        path="/v1/containers",
        python_sdk_call="client.containers.create(...)",
        input_modalities=("file", "text", "mixed"),
        output_modalities=("structured_data",),
        supports_mixed_content=True,
        notes="Container lifecycle surface used by hosted execution environments.",
        category="containers",
        documented_operations=("create", "retrieve", "delete", "list"),
        documented_subresources=("/v1/containers/{container_id}",),
    ),
    _endpoint(
        name="container_files",
        path="/v1/containers/{container_id}/files",
        python_sdk_call="client.containers.files.create(...)",
        input_modalities=("file", "text"),
        output_modalities=("structured_data", "file"),
        supports_mixed_content=False,
        notes="Container file management surface, including raw content retrieval.",
        category="containers",
        documented_operations=("list", "create", "retrieve", "delete", "retrieve_content"),
        documented_subresources=(
            "/v1/containers/{container_id}/files/{file_id}",
            "/v1/containers/{container_id}/files/{file_id}/content",
        ),
    ),
    _endpoint(
        name="skills",
        path="/v1/skills",
        python_sdk_call="client.skills.create(...)",
        input_modalities=("text", "file", "mixed"),
        output_modalities=("structured_data",),
        supports_mixed_content=True,
        notes="Skill registry surface with versioned skill content management.",
        category="skills",
        documented_operations=("create", "retrieve", "retrieve_content", "update", "delete", "list", "create_version", "retrieve_version", "retrieve_version_content", "delete_version", "list_versions"),
        documented_subresources=(
            "/v1/skills/{skill_id}",
            "/v1/skills/{skill_id}/content",
            "/v1/skills/{skill_id}/versions",
            "/v1/skills/{skill_id}/versions/{version_id}",
            "/v1/skills/{skill_id}/versions/{version_id}/content",
        ),
    ),
    _endpoint(
        name="realtime",
        path="/v1/realtime",
        python_sdk_call="OpenAI realtime session via WebRTC/WebSocket/SIP",
        input_modalities=("text", "audio", "image", "mixed"),
        output_modalities=("text", "audio", "events"),
        supports_mixed_content=True,
        notes="Realtime surface for low-latency multimodal interaction plus call control and client-secret bootstrap.",
        category="realtime",
        documented_operations=("create_client_secret", "accept_call", "hangup_call", "refer_call", "reject_call", "client_events", "server_events"),
        documented_subresources=(
            "/v1/realtime/client_secrets",
            "/v1/realtime/calls/{call_id}/accept",
            "/v1/realtime/calls/{call_id}/hangup",
            "/v1/realtime/calls/{call_id}/refer",
            "/v1/realtime/calls/{call_id}/reject",
        ),
    ),
    _endpoint(
        name="organization_administration",
        path="/v1/organization",
        python_sdk_call="OpenAI administration HTTP API",
        input_modalities=(),
        output_modalities=("structured_data",),
        supports_mixed_content=False,
        notes="Administration surface covering costs, audit logs, admin API keys, usage, invites, users, groups, roles, certificates, and organization-scoped projects.",
        category="administration",
        lifecycle="admin",
        documented_operations=("get_costs", "list_audit_logs", "admin_api_keys", "usage", "invites", "users", "groups", "roles", "certificates", "projects"),
        documented_subresources=(
            "/v1/organization/costs",
            "/v1/organization/audit_logs",
            "/v1/organization/admin_api_keys",
            "/v1/organization/usage",
            "/v1/organization/invites",
            "/v1/organization/users",
            "/v1/organization/groups",
            "/v1/organization/roles",
            "/v1/organization/certificates",
            "/v1/organization/projects",
        ),
    ),
    _endpoint(
        name="project_administration",
        path="/v1/projects",
        python_sdk_call="OpenAI project administration HTTP API",
        input_modalities=(),
        output_modalities=("structured_data",),
        supports_mixed_content=False,
        notes="Project-scoped administration surface for roles and project-membership role bindings.",
        category="administration",
        lifecycle="admin",
        documented_operations=("roles", "group_roles", "user_roles"),
        documented_subresources=(
            "/v1/projects/{project_id}/roles",
            "/v1/projects/{project_id}/groups/{group_id}/roles",
            "/v1/projects/{project_id}/users/{user_id}/roles",
        ),
    ),
    _endpoint(
        name="assistants_legacy",
        path="/v1/assistants",
        python_sdk_call="client.beta.assistants.create(...)",
        input_modalities=("text", "image", "file", "mixed"),
        output_modalities=("text", "tool_calls", "structured_data"),
        supports_mixed_content=True,
        notes="Legacy Assistants family retained for migration support, including assistants, threads, messages, runs, and tool-output submission.",
        category="legacy",
        lifecycle="legacy",
        documented_operations=("create", "retrieve", "update", "delete", "list", "threads", "messages", "runs", "submit_tool_outputs", "stream_events"),
        documented_subresources=(
            "/v1/threads",
            "/v1/threads/{thread_id}",
            "/v1/threads/{thread_id}/messages",
            "/v1/threads/{thread_id}/runs",
            "/v1/threads/{thread_id}/runs/{run_id}",
            "/v1/threads/{thread_id}/runs/{run_id}/submit_tool_outputs",
        ),
    ),
    _endpoint(
        name="completions_legacy",
        path="/v1/completions",
        python_sdk_call="client.completions.create(...)",
        input_modalities=("text",),
        output_modalities=("text", "structured_data"),
        supports_mixed_content=False,
        notes="Legacy text completion surface kept for compatibility and migration audits.",
        category="legacy",
        lifecycle="legacy",
        documented_operations=("create",),
    ),
    _endpoint(
        name="realtime_beta_legacy",
        path="/v1/realtime",
        python_sdk_call="Legacy Realtime Beta session APIs",
        input_modalities=("audio", "text"),
        output_modalities=("events", "text"),
        supports_mixed_content=False,
        notes="Legacy realtime beta surface covering session creation and transcription session creation.",
        category="legacy",
        lifecycle="legacy",
        documented_operations=("create_session", "create_transcription_session"),
        documented_subresources=(
            "/v1/realtime/sessions",
            "/v1/realtime/transcription_sessions",
        ),
    ),
)

OPENAI_HTTP_ENDPOINTS: tuple[str, ...] = (
    "POST /v1/responses",
    "GET /v1/responses/{response_id}",
    "DELETE /v1/responses/{response_id}",
    "GET /v1/responses/{response_id}/input_items",
    "POST /v1/responses/input_tokens",
    "POST /v1/responses/{response_id}/cancel",
    "POST /v1/responses/compact",
    "POST /v1/conversations",
    "GET /v1/conversations/{conversation_id}",
    "POST /v1/conversations/{conversation_id}",
    "DELETE /v1/conversations/{conversation_id}",
    "POST /v1/conversations/{conversation_id}/items",
    "GET /v1/conversations/{conversation_id}/items",
    "GET /v1/conversations/{conversation_id}/items/{item_id}",
    "DELETE /v1/conversations/{conversation_id}/items/{item_id}",
    "POST /v1/chat/completions",
    "GET /v1/chat/completions",
    "GET /v1/chat/completions/{completion_id}",
    "POST /v1/chat/completions/{completion_id}",
    "DELETE /v1/chat/completions/{completion_id}",
    "GET /v1/chat/completions/{completion_id}/messages",
    "POST /v1/realtime/client_secrets",
    "POST /v1/realtime/calls/{call_id}/accept",
    "POST /v1/realtime/calls/{call_id}/hangup",
    "POST /v1/realtime/calls/{call_id}/refer",
    "POST /v1/realtime/calls/{call_id}/reject",
    "POST /v1/realtime/sessions",
    "POST /v1/realtime/transcription_sessions",
    "POST /v1/audio/transcriptions",
    "POST /v1/audio/translations",
    "POST /v1/audio/speech",
    "POST /v1/audio/voices",
    "GET /v1/audio/voice_consents",
    "POST /v1/audio/voice_consents",
    "GET /v1/audio/voice_consents/{consent_id}",
    "POST /v1/audio/voice_consents/{consent_id}",
    "DELETE /v1/audio/voice_consents/{consent_id}",
    "POST /v1/videos",
    "GET /v1/videos",
    "GET /v1/videos/{video_id}",
    "DELETE /v1/videos/{video_id}",
    "GET /v1/videos/{video_id}/content",
    "POST /v1/videos/edits",
    "POST /v1/videos/extensions",
    "POST /v1/videos/{video_id}/remix",
    "POST /v1/videos/characters",
    "GET /v1/videos/characters/{character_id}",
    "POST /v1/images/generations",
    "POST /v1/images/edits",
    "POST /v1/images/variations",
    "POST /v1/embeddings",
    "POST /v1/moderations",
    "GET /v1/files",
    "POST /v1/files",
    "GET /v1/files/{file_id}",
    "DELETE /v1/files/{file_id}",
    "GET /v1/files/{file_id}/content",
    "POST /v1/uploads",
    "POST /v1/uploads/{upload_id}/complete",
    "POST /v1/uploads/{upload_id}/cancel",
    "POST /v1/uploads/{upload_id}/parts",
    "POST /v1/batches",
    "GET /v1/batches",
    "GET /v1/batches/{batch_id}",
    "POST /v1/batches/{batch_id}/cancel",
    "GET /v1/models",
    "GET /v1/models/{model}",
    "DELETE /v1/models/{model}",
    "POST /v1/fine_tuning/jobs",
    "GET /v1/fine_tuning/jobs",
    "GET /v1/fine_tuning/jobs/{fine_tuning_job_id}",
    "GET /v1/fine_tuning/jobs/{fine_tuning_job_id}/events",
    "POST /v1/fine_tuning/jobs/{fine_tuning_job_id}/cancel",
    "POST /v1/fine_tuning/jobs/{fine_tuning_job_id}/pause",
    "POST /v1/fine_tuning/jobs/{fine_tuning_job_id}/resume",
    "GET /v1/fine_tuning/checkpoints/{fine_tuned_model_checkpoint}/permissions",
    "POST /v1/fine_tuning/checkpoints/{fine_tuned_model_checkpoint}/permissions",
    "DELETE /v1/fine_tuning/checkpoints/{fine_tuned_model_checkpoint}/permissions/{permission_id}",
    "POST /v1/fine_tuning/alpha/graders/run",
    "POST /v1/fine_tuning/alpha/graders/validate",
    "GET /v1/vector_stores",
    "POST /v1/vector_stores",
    "GET /v1/vector_stores/{vector_store_id}",
    "POST /v1/vector_stores/{vector_store_id}",
    "DELETE /v1/vector_stores/{vector_store_id}",
    "POST /v1/vector_stores/{vector_store_id}/search",
    "GET /v1/vector_stores/{vector_store_id}/files",
    "POST /v1/vector_stores/{vector_store_id}/files",
    "GET /v1/vector_stores/{vector_store_id}/files/{file_id}",
    "POST /v1/vector_stores/{vector_store_id}/files/{file_id}",
    "DELETE /v1/vector_stores/{vector_store_id}/files/{file_id}",
    "POST /v1/vector_stores/{vector_store_id}/file_batches",
    "GET /v1/vector_stores/{vector_store_id}/file_batches/{batch_id}",
    "GET /v1/vector_stores/{vector_store_id}/file_batches/{batch_id}/files",
    "POST /v1/vector_stores/{vector_store_id}/file_batches/{batch_id}/cancel",
    "GET /v1/evals",
    "POST /v1/evals",
    "GET /v1/evals/{eval_id}",
    "POST /v1/evals/{eval_id}",
    "DELETE /v1/evals/{eval_id}",
    "GET /v1/evals/{eval_id}/runs",
    "POST /v1/evals/{eval_id}/runs",
    "GET /v1/evals/{eval_id}/runs/{run_id}",
    "POST /v1/evals/{eval_id}/runs/{run_id}",
    "DELETE /v1/evals/{eval_id}/runs/{run_id}",
    "GET /v1/containers",
    "POST /v1/containers",
    "GET /v1/containers/{container_id}",
    "DELETE /v1/containers/{container_id}",
    "GET /v1/containers/{container_id}/files",
    "POST /v1/containers/{container_id}/files",
    "GET /v1/containers/{container_id}/files/{file_id}",
    "DELETE /v1/containers/{container_id}/files/{file_id}",
    "GET /v1/containers/{container_id}/files/{file_id}/content",
    "GET /v1/assistants",
    "POST /v1/assistants",
    "GET /v1/assistants/{assistant_id}",
    "POST /v1/assistants/{assistant_id}",
    "DELETE /v1/assistants/{assistant_id}",
    "POST /v1/threads",
    "POST /v1/threads/runs",
    "GET /v1/threads/{thread_id}",
    "POST /v1/threads/{thread_id}",
    "DELETE /v1/threads/{thread_id}",
    "GET /v1/threads/{thread_id}/messages",
    "POST /v1/threads/{thread_id}/messages",
    "GET /v1/threads/{thread_id}/messages/{message_id}",
    "POST /v1/threads/{thread_id}/messages/{message_id}",
    "DELETE /v1/threads/{thread_id}/messages/{message_id}",
    "GET /v1/threads/{thread_id}/runs",
    "POST /v1/threads/{thread_id}/runs",
    "GET /v1/threads/{thread_id}/runs/{run_id}",
    "POST /v1/threads/{thread_id}/runs/{run_id}",
    "POST /v1/threads/{thread_id}/runs/{run_id}/submit_tool_outputs",
    "POST /v1/threads/{thread_id}/runs/{run_id}/cancel",
    "GET /v1/threads/{thread_id}/runs/{run_id}/steps",
    "GET /v1/threads/{thread_id}/runs/{run_id}/steps/{step_id}",
)


def endpoints_for_modality(modality: str) -> list[OpenAIEndpointSpec]:
    normalized = modality.strip().lower()
    return [
        endpoint
        for endpoint in OPENAI_ENDPOINTS
        if normalized in endpoint.input_modalities or normalized in endpoint.output_modalities
    ]


def endpoints_for_category(category: str) -> list[OpenAIEndpointSpec]:
    normalized = category.strip().lower()
    return [endpoint for endpoint in OPENAI_ENDPOINTS if endpoint.category == normalized]


def endpoints_for_lifecycle(lifecycle: str) -> list[OpenAIEndpointSpec]:
    normalized = lifecycle.strip().lower()
    return [endpoint for endpoint in OPENAI_ENDPOINTS if endpoint.lifecycle == normalized]


__all__ = [
    "OPENAI_HTTP_ENDPOINTS",
    "OPENAI_ENDPOINTS",
    "OpenAIEndpointSpec",
    "endpoints_for_category",
    "endpoints_for_lifecycle",
    "endpoints_for_modality",
]
