"""Public surface for the OpenAgentBench memory module."""

from .budgeting import allocate_layer_budgets, compute_working_memory_capacity, reallocate_for_procedure_match
from .compiler import MemoryContextCompiler, filter_scoped_memories
from .endpoint_compat import (
    MemoryEndpointCompatibilityReport,
    assert_memory_endpoint_payload_compatibility,
    build_memory_endpoint_compatibility_report,
    build_memory_inspect_tool_definition,
    build_memory_read_tool_definition,
    build_memory_write_tool_definition,
)
from .enums import (
    ConflictResolution,
    ConflictStatus,
    MemoryOperation,
    ProcedureMatchMode,
    ProcedureStatus,
    PromotionAction,
    PromotionSource,
    RecallMode,
)
from .models import (
    BudgetAllocation,
    CompiledMemoryContext,
    MemoryAuditRecord,
    MemoryCacheEntry,
    MemoryCompileRequest,
    MemoryFragment,
    MemoryMaintenanceReport,
    MemoryRepositorySnapshot,
    MemoryWritePlan,
    ProcedureMatchResult,
    PromotionCandidate,
    PromotionDecision,
    QueryTemplate,
    SessionCheckpointRecord,
    SessionTurnMarkers,
    WorkingMemoryItem,
    WorkingMemorySnapshot,
    new_checkpoint,
)
from .promotion import AUTHORITY_RANK, decide_promotion, determine_target_layer, resolve_authority_conflict
from .providers import (
    EmbeddingProvider,
    HashingEmbeddingProvider,
    HeuristicMemoryTextModel,
    MemoryProviderSuite,
    OpenAICompatibleEmbeddingProvider,
    OpenAICompatibleTextModel,
    TextModel,
)
from .queries import (
    build_insert_memory_audit_log,
    build_insert_memory_cache_entry,
    build_insert_session_checkpoint,
    build_invalidate_memory_cache,
    build_load_durable_memories,
    build_load_working_memory,
    build_lookup_memory_cache,
)
from .repository import InMemoryMemoryRepository, MemoryRepository
from .runtime import module_root, plan_path, read_plan, read_schema_sql, schema_sql_path
from .scoring import (
    candidate_promotion_score,
    effective_ttl_days,
    episodic_recall_score,
    memory_record_priority,
    promotion_score,
    working_memory_utility,
)
from .session import build_session_checkpoint, detect_turn_markers, project_turn_text, update_session_summary
from .working import EXPENSIVE_MODALITIES, WorkingMemoryBuffer

__all__ = [
    "AUTHORITY_RANK",
    "BudgetAllocation",
    "CompiledMemoryContext",
    "ConflictResolution",
    "ConflictStatus",
    "EmbeddingProvider",
    "EXPENSIVE_MODALITIES",
    "HashingEmbeddingProvider",
    "HeuristicMemoryTextModel",
    "InMemoryMemoryRepository",
    "MemoryAuditRecord",
    "MemoryCacheEntry",
    "MemoryCompileRequest",
    "MemoryContextCompiler",
    "MemoryEndpointCompatibilityReport",
    "MemoryFragment",
    "MemoryMaintenanceReport",
    "MemoryOperation",
    "MemoryProviderSuite",
    "MemoryRepository",
    "MemoryRepositorySnapshot",
    "MemoryWritePlan",
    "OpenAICompatibleEmbeddingProvider",
    "OpenAICompatibleTextModel",
    "ProcedureMatchMode",
    "ProcedureMatchResult",
    "ProcedureStatus",
    "PromotionAction",
    "PromotionCandidate",
    "PromotionDecision",
    "PromotionSource",
    "QueryTemplate",
    "RecallMode",
    "SessionCheckpointRecord",
    "SessionTurnMarkers",
    "TextModel",
    "WorkingMemoryBuffer",
    "WorkingMemoryItem",
    "WorkingMemorySnapshot",
    "allocate_layer_budgets",
    "assert_memory_endpoint_payload_compatibility",
    "build_insert_memory_audit_log",
    "build_insert_memory_cache_entry",
    "build_insert_session_checkpoint",
    "build_invalidate_memory_cache",
    "build_load_durable_memories",
    "build_load_working_memory",
    "build_lookup_memory_cache",
    "build_memory_endpoint_compatibility_report",
    "build_memory_inspect_tool_definition",
    "build_memory_read_tool_definition",
    "build_memory_write_tool_definition",
    "build_session_checkpoint",
    "candidate_promotion_score",
    "compute_working_memory_capacity",
    "decide_promotion",
    "detect_turn_markers",
    "determine_target_layer",
    "effective_ttl_days",
    "episodic_recall_score",
    "filter_scoped_memories",
    "memory_record_priority",
    "module_root",
    "new_checkpoint",
    "plan_path",
    "project_turn_text",
    "promotion_score",
    "read_plan",
    "read_schema_sql",
    "reallocate_for_procedure_match",
    "resolve_authority_conflict",
    "schema_sql_path",
    "update_session_summary",
    "working_memory_utility",
]
